n=input('Digite algo: ')
print('O tipo desse valor é ', type(n))
print('É alfabetico? ', n.isalpha())
print('É minúsculo? ',n.islower())
print('Tem espaço? ',n.isspace())
print('É número? ', n.isalnum())
print('Esta capitalizada? ', n.istitle())